version: '3'
services:
  mysql_container:
    image: mysql:latest
    container_name: mysql_db_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: koifengshui
    ports:
      - "3307:3306"

  app:
    image: hieuphi/koifengshui:v3
    container_name: springboot_container
    environment:
      MYSQL_URL: "jdbc:mysql://mysql_container:3306/koifengshui"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
    depends_on:
      - mysql_container
    ports:
      - "8081:8080"
